import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import User from "./components/User";
import Header from "./components/Header";
import { ScanProvider } from "./context/ScanContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ScanProvider>
          <Header />
          <User />
          {children}
        </ScanProvider>
      </body>
    </html>
  );
}
